name: Notion Deadline Updater

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  update-deadlines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installa dipendenze
        run: pip install -r requirements.txt

      - name: Esegui script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION }}
        run: python notion_deadline_updater.py
